### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by msarguru** [lcrawlab/MELD#1]
Hi, thank you for the iLDSC. Trying it on a sumstat.gz that works for LDSC, returns the index out of range error. and I am using the following syntax.
Any suggestions, would be greatly appreciated.
./ldsc.py \
--h2 ../sumstats/PSS.EUR.pdt10.nomerge.sumstats.gz \
--ref-ld-chr ./EUR_1000G/Full_cisLD/ \
--out WMH_EUR_ildsc \
--w-ld-chr ../ldsc/eur_w_ld_chr/ \
--print-coefficients 

Beginning analysis at Wed Aug 14 20:19:44 2024
Reading summary statistics from ../sumstats/PSS.EUR.pdt10.nomerge.sumstats.gz ...
Read summary statistics for 5355832 SNPs.
Reading reference panel LD Score from ./EUR_1000G/Full_cisLD/[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "ildsc.py", line 651, in <module>
    sumstats.estimate_h2(args, log)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 245, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 154, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/annotation/ldsc-F/ildsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/annotation/ldsc-F/ildsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

Analysis finished at Wed Aug 14 20:19:53 2024
Total time elapsed: 9.15s
Traceback (most recent call last):
  File "ildsc.py", line 651, in <module>
    sumstats.estimate_h2(args, log)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 329, in estimate_h2
    args, log, args.h2)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 245, in _read_ld_sumstats
    ref_ld = _read_ref_ld(args, log)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 82, in _read_ref_ld
    'reference panel LD Score', ps.ldscore_fromlist)
  File "/annotation/ldsc-F/ildsc/ldscore/sumstats.py", line 154, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/annotation/ldsc-F/ildsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/annotation/ldsc-F/ildsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

**Comment by msarguru** [comment]
Update. Got this sorted, turned out issue with the filenaming.. also few suggestions on the readme for git.. one has to use 
git sparse-checkout set --no-cone \* 
to get all the required ldscore files.

Would love an addition on the interpretation of the output.. what each column refers to, etc. Thanks again
